### PR TITLE
tiny update for Ender.js

### PR DESCRIPTION
**Pull request by ded**
it's been a while — and I've been using an old version of `when`. But alas I went to upgrade and it appears there are some new files in the updated when version. would you mind adding this one item?

### CODE REVIEW

**Comment by ded** [comment]
oh dear goodness... it shows 3 commits. let me know if you need me to squash that for you.

**Comment by briancavalier** [comment]
Hey @ded!  Sorry about that, thanks for jumping in with the fix :)  Yeah, please squash and I'll get this merged and released.

**Comment by briancavalier** [comment]
Ping @ded.  Can you squash this?  Thanks!

**Comment by briancavalier** [comment]
@ded Merged and squashed in 1bbc998. Thanks again!

**Pull request closed without merging**
