### PR TITLE
Add better callbacks.call example

### LINKED ISSUE #460: callbacks.call example doesn't work
```
$ node --version
v0.10.35
```

```
var callbacks = require("when/callbacks");
var waitFiveSeconds = callbacks.call(setTimeout, 5000);
timers.js:219
      callback.apply(timer, args);
               ^
TypeError: Object 5000 has no method 'apply'
    at timer._onTimeout (timers.js:219:16)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

### PR DESCRIPTION
**Pull request by briancavalier**
Fix #460

### CODE REVIEW

**Comment by unscriptable** [comment]
:+1:

**Comment by ceineke** [comment]
So, does callbacks.call require the last two arguments exactly to be the node-style callbacks? Or is one enough?

**Comment by briancavalier** [comment]
@ceineke The last two arguments should be "normal" callbacks (i.e. each accepts a single parameter), rather than node-style callbacks.  They work like the `resolve` and `reject` parameters passed in the ES6 Promise constructor.

Yes, using a single callback is enough--you can ignore the `reject` parameter if you don't need it, just like you can ignore it when using an ES6 Promise constructor or `when.promise`.  For example, these two are equivalent:

```js
// Declare both resolve and reject as parameters
callbacks.call((x, y, z, resolve, reject) => resolve(x+y+z), 10, 20, 30); // promise for 60

// Don't declare reject because it isn't needed
callbacks.call((x, y, z, resolve) => resolve(x+y+z), 10, 20, 30); // promise for 60
```

Make sense?

**Comment by ceineke** [comment]
Gotcha. :) :+1:

**Pull request merged**
