### PR TITLE
Use latest buster from git

### PR DESCRIPTION
**Pull request by dominykas**
Please keep this open - it will spare me the trouble of setting up extra travis/saucelabs builds while I'm upgrading buster's dependencies.

Thanks :)

### CODE REVIEW

**Comment by dominykas** [comment]
Not bad! Only fails on Chrome latest and IE11 :) And I even have a suspicion why...

**Comment by dominykas** [comment]
OK, IE failure seems to be due to https://github.com/sinonjs/sinon/pull/858 (merged, but not published just yet?)

**Comment by briancavalier** [comment]
> Please keep this open

Sure, no problem

**Comment by briancavalier** [comment]
@dominykas Are you still using this?

**Comment by dominykas** [comment]
Yes, I'd like to go end to end after browserified version is out. Might also have to take time to port some changes from sinon 2-pre to 1.9...

**Pull request closed without merging**
